# Generated by Django 2.1.3 on 2018-12-30 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='업체명')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('field', models.CharField(max_length=200, verbose_name='검사분야')),
                ('phone_number', models.CharField(max_length=200, verbose_name='연락처')),
            ],
        ),
        migrations.AddField(
            model_name='qualitytest',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='quality_test.TestInstitution', verbose_name='검사업체'),
        ),
        migrations.AddField(
            model_name='qualitytest',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='recipe.Recipe', verbose_name='레시피'),
        ),
        migrations.AddField(
            model_name='qualitytest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
