# Generated by Django 2.1.2 on 2018-12-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitytest',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='quality_test.TestInstitution', verbose_name='검사업체'),
        ),
        migrations.AlterField(
            model_name='qualitytest',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='recipe.Recipe', verbose_name='레시피'),
        ),
        migrations.AlterField(
            model_name='testinstitution',
            name='address',
            field=models.CharField(max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='testinstitution',
            name='field',
            field=models.CharField(max_length=200, verbose_name='검사분야'),
        ),
        migrations.AlterField(
            model_name='testinstitution',
            name='name',
            field=models.CharField(max_length=200, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='testinstitution',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='연락처'),
        ),
    ]
