# Generated by Django 2.1.3 on 2018-12-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=200)),
                ('lecture_option', models.TextField()),
                ('lecture_price', models.PositiveIntegerField(default=0)),
                ('lecture_total_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
