# Generated by Django 2.1.2 on 2018-12-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=200)),
                ('lecture_option', models.TextField()),
                ('lecture_price', models.PositiveIntegerField(default=0)),
                ('lecture_total_count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='stores.Store')),
            ],
        ),
    ]
