# Generated by Django 2.1.2 on 2018-12-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='레시피명')),
                ('type', models.CharField(max_length=200, verbose_name='상품유형')),
                ('capacity', models.TextField(verbose_name='내용량')),
                ('manufacturing_method', models.TextField(verbose_name='제조방법')),
                ('packing_material', models.TextField(verbose_name='포장방법')),
                ('preservation_method', models.TextField(verbose_name='보존방법')),
                ('expiration_date', models.TextField(verbose_name='유통기한')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
