# Generated by Django 2.1.2 on 2018-12-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='method',
            new_name='manufacturing_method',
        ),
        migrations.AddField(
            model_name='recipe',
            name='preservation_method',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
