# Generated by Django 2.1.2 on 2018-12-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='capacity',
            field=models.TextField(verbose_name='내용량'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='expiration_date',
            field=models.TextField(verbose_name='유통기한'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='manufacturing_method',
            field=models.TextField(verbose_name='제조방법'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='레시피명'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='packing_material',
            field=models.TextField(verbose_name='포장방법'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preservation_method',
            field=models.TextField(verbose_name='보존방법'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(max_length=200, verbose_name='상품유형'),
        ),
    ]
