# Generated by Django 2.1.2 on 2018-11-30 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('cancel_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_option', models.TextField()),
                ('product_price', models.PositiveIntegerField(default=0)),
                ('product_total_count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.Store')),
            ],
        ),
        migrations.AddField(
            model_name='ordering',
            name='ordering_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering', to='products.OrderingInfo'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering', to='products.Product'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
