# Generated by Django 2.1.2 on 2018-12-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
