# Generated by Django 2.1.2 on 2018-12-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
