# Generated by Django 2.1.3 on 2018-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_comparison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='제품링크'),
        ),
    ]
