# Generated by Django 2.1.2 on 2018-12-19 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients_labeling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calorie', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('carbohydrate', models.FloatField(default=0)),
                ('sugars', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('trans_fatty_acid', models.FloatField(default=0)),
                ('saturated_fatty_acid', models.FloatField(default=0)),
                ('cholesterol', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('dietary_fiber', models.FloatField(default=0)),
                ('vitamin_a', models.FloatField(default=0)),
                ('thiamine', models.FloatField(default=0)),
                ('riboflavin', models.FloatField(default=0)),
                ('niacin', models.FloatField(default=0)),
                ('pantothenic_acid', models.FloatField(default=0)),
                ('pyridoxine', models.FloatField(default=0)),
                ('biotin', models.FloatField(default=0)),
                ('folic_acid', models.FloatField(default=0)),
                ('cyanocobalamin', models.FloatField(default=0)),
                ('vitamin_c', models.FloatField(default=0)),
                ('vitamin_d', models.FloatField(default=0)),
                ('vitamin_e', models.FloatField(default=0)),
                ('vitamin_k', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('phosphorus', models.FloatField(default=0)),
                ('potassium', models.FloatField(default=0)),
                ('magnesium', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
                ('zinc', models.FloatField(default=0)),
                ('copper', models.FloatField(default=0)),
                ('manganese', models.FloatField(default=0)),
                ('iodine', models.FloatField(default=0)),
                ('selenium', models.FloatField(default=0)),
                ('molybdenum', models.FloatField(default=0)),
                ('chromium', models.FloatField(default=0)),
                ('alcohol', models.FloatField(default=0)),
                ('organic_acid', models.FloatField(default=0)),
                ('sugar_alcohol', models.FloatField(default=0)),
                ('erythritol', models.FloatField(default=0)),
                ('tagatose', models.FloatField(default=0)),
                ('allulose', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsLabeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('original_weight', models.PositiveIntegerField(default=0)),
                ('product_weight', models.PositiveIntegerField(default=0)),
                ('weight_change_rate', models.FloatField(default=0)),
                ('total_weight', models.PositiveIntegerField(default=0)),
                ('total_unit_count', models.PositiveIntegerField(default=0)),
                ('single_unit_capacity', models.PositiveIntegerField(default=0)),
                ('unit_type', models.CharField(choices=[('g', '그램'), ('ml', '밀리리터')], max_length=2)),
                ('unit_count_type', models.CharField(max_length=200)),
                ('specific_gravity', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_labeling', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredients_labeling',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredients_labeling.IngredientsLabeling'),
        ),
    ]
