# Generated by Django 2.1.3 on 2018-12-30 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients_labeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientslabeling',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_labeling', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredients_labeling',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredients_labeling.IngredientsLabeling', verbose_name='영양성분표'),
        ),
    ]
