# Generated by Django 2.1.2 on 2018-12-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_labeling', '0002_auto_20181223_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='unit_type',
            field=models.CharField(choices=[('g', '그램'), ('ml', '밀리리터')], default='g', max_length=2, verbose_name='단위'),
        ),
    ]
