# Generated by Django 2.1.2 on 2018-12-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_labeling', '0002_auto_20181219_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calorie',
            field=models.PositiveIntegerField(default=0, verbose_name='칼로리'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='용량'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrate',
            field=models.FloatField(default=0, verbose_name='탄수화물'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cholesterol',
            field=models.FloatField(default=0, verbose_name='콜레스테롤'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(default=0, verbose_name='지방'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=0, verbose_name='단백질'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='saturated_fatty_acid',
            field=models.FloatField(default=0, verbose_name='포화지방'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.FloatField(default=0, verbose_name='나트륨'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugars',
            field=models.FloatField(default=0, verbose_name='당류'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='trans_fatty_acid',
            field=models.FloatField(default=0, verbose_name='트랜스지방'),
        ),
    ]
