# Generated by Django 2.1.3 on 2018-12-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_labeling', '0002_auto_20181230_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='date',
            field=models.DateField(editable=False),
        ),
    ]
