# Generated by Django 2.1.2 on 2018-12-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_labeling', '0003_auto_20181219_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientslabeling',
            name='gravity_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='무게'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredients_labeling',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredients_labeling.IngredientsLabeling', verbose_name='영양성분표'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='name',
            field=models.CharField(max_length=200, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='original_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='초기중량(g)'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='product_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='제조후중량(g)'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='single_unit_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='단위내용량'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='specific_gravity',
            field=models.FloatField(default=0, verbose_name='비중'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='total_unit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='단위수'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='total_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='총내용량(g)'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='unit_count_type',
            field=models.CharField(default='1개', max_length=200, verbose_name='세는 단위'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='unit_type',
            field=models.CharField(choices=[('g', '그램'), ('ml', '밀리리터')], max_length=2, verbose_name='단위'),
        ),
        migrations.AlterField(
            model_name='ingredientslabeling',
            name='weight_change_rate',
            field=models.FloatField(default=0, verbose_name='중량변화율(%)'),
        ),
    ]
