# Generated by Django 2.1.2 on 2018-12-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcalculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemregister',
            name='cost_per_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costcalculator',
            name='usage',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
