# Generated by Django 2.1.2 on 2018-12-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcalculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcalculator',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculators', to='costcalculator.Material', verbose_name='재료'),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='판매개수'),
        ),
        migrations.AlterField(
            model_name='item',
            name='margin',
            field=models.FloatField(default=0, verbose_name='마진'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='판매가격'),
        ),
        migrations.AlterField(
            model_name='item',
            name='prime_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='원가'),
        ),
        migrations.AlterField(
            model_name='item',
            name='profit',
            field=models.IntegerField(default=0, verbose_name='이익'),
        ),
        migrations.AlterField(
            model_name='material',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='용량'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cost_per_one',
            field=models.IntegerField(default=0, verbose_name='1g당 가격'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, verbose_name='재료명'),
        ),
    ]
