# Generated by Django 2.1.2 on 2018-12-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcalculator', '0002_auto_20181221_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcalculator',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calculators', to='costcalculator.Item', verbose_name='제품'),
            preserve_default=False,
        ),
    ]
