# Generated by Django 2.1.2 on 2018-12-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
        ('shopping_carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='lectures.Lecture'),
            preserve_default=False,
        ),
    ]
